'use client';

import { useCallback,useEffect,useState } from 'react';
import { ApiError,apiFetch } from '../../lib/api';
import { getAccessToken } from '../../lib/auth';

type N={id:string;channel:string;recipient:string;eventType:string;status:string;attempts:number;lastError?:string|null;createdAt:string;updatedAt:string;sentAt?:string|null;availableAt?:string|null};
type Stats={PENDING:number;PROCESSING:number;SENT:number;FAILED:number;CANCELED:number};
function fmt(v?:string|null){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'Invalid timestamp':d.toLocaleString();}
export default function NotificationsPage(){const [rows,setRows]=useState<N[]>([]);const [stats,setStats]=useState<Stats>({PENDING:0,PROCESSING:0,SENT:0,FAILED:0,CANCELED:0});const [loading,setLoading]=useState(true);const [recovering,setRecovering]=useState(false);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{const t=getAccessToken();if(!t){setError('Authentication required.');setLoading(false);return;}setLoading(true);setError(null);try{const h={Authorization:`Bearer ${t}`};const [l,s]=await Promise.all([apiFetch<{data:N[]}>('/notifications/outbox?limit=100',{headers:h}),apiFetch<Stats>('/notifications/stats',{headers:h})]);setRows(Array.isArray(l.data)?l.data:[]);setStats(s);}catch(e:unknown){setError(e instanceof ApiError||e instanceof Error?e.message:'Unable to load notification operations.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]); async function recover(){const t=getAccessToken();if(!t)return;setRecovering(true);setError(null);try{await apiFetch('/notifications/recover-stale?maxAgeMinutes=15',{method:'POST',headers:{Authorization:`Bearer ${t}`}});await load()}catch(e:unknown){setError(e instanceof ApiError||e instanceof Error?e.message:'Unable to recover stale notifications.')}finally{setRecovering(false)}}
 return <main className="app-shell"><section className="content" style={{marginLeft:0,width:'100%'}}><header className="topbar"><div><div className="eyebrow">JASLYN NET / OPERATIONS</div><h1>Notification operations</h1><p className="context">Tenant-scoped notification outbox health, delivery state and stale-processing recovery.</p></div><div className="top-actions"><button className="selector" onClick={()=>void recover()} disabled={recovering}>{recovering?'Recovering…':'Recover stale'}</button><button className="selector" onClick={()=>void load()} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button></div></header>{error&&<div className="error-banner" role="alert">{error}</div>}
 <section className="kpi-grid">{Object.entries(stats).map(([k,v])=><article className="kpi" key={k}><div className="kpi-label"><span>{k}</span></div><strong>{v}</strong><div className="kpi-foot"><span>OUTBOX</span><small>current state</small></div></article>)}</section>
 <section className="panel"><div className="panel-head"><div><div className="panel-kicker">DELIVERY OUTBOX</div><h2>Recent notifications</h2><p>Recipients and delivery errors are shown because this is an authenticated operator surface.</p></div></div><div className="table-wrap"><table><thead><tr><th>EVENT</th><th>CHANNEL</th><th>RECIPIENT</th><th>STATUS</th><th>ATTEMPTS</th><th>AVAILABLE</th><th>LAST ERROR</th><th>CREATED</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.eventType}</strong><br/><small>{r.id.slice(0,8)}…</small></td><td>{r.channel}</td><td>{r.recipient}</td><td><span className={`status ${r.status.toLowerCase()}`}><i/>{r.status}</span></td><td>{r.attempts}</td><td>{fmt(r.availableAt)}</td><td><small className="row-error">{r.lastError??'—'}</small></td><td>{fmt(r.createdAt)}</td></tr>)}</tbody></table>{!loading&&!rows.length&&<div className="empty-state"><strong>No notification records.</strong><span>The tenant outbox is currently empty.</span></div>}{loading&&<div className="empty-state">Loading notification outbox…</div>}</div></section>
 <footer className="footer"><span>JASLYN NET · Notification Operations</span><span>Owner / Admin access</span></footer><style jsx>{`.row-error{display:block;color:#7d899a;max-width:260px;white-space:normal}`}</style></section></main>}
