'use client';
import { FormEvent, useEffect, useState } from 'react';
import { getAccessToken } from '../../lib/auth';
import { apiFetch } from '../../lib/api';
type Customer={id:string;username?:string|null;fullName?:string|null;email?:string|null;phone?:string|null;isActive?:boolean;createdAt?:string};
type Response={data:Customer[];pagination:{page:number;limit:number;total:number;pages:number}};
type Sale={orderId:string;customerId:string;phone?:string;paymentReference?:string;packageName:string;startsAt:string;endsAt:string;amount:number|string;currency:string};
export default function CustomersPage(){
 const [customers,setCustomers]=useState<Customer[]>([]),[search,setSearch]=useState(''),[page,setPage]=useState(1),[pagination,setPagination]=useState<Response['pagination']>({page:1,limit:25,total:0,pages:0}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[form,setForm]=useState({fullName:'',username:'',email:'',phone:''}),[saving,setSaving]=useState(false);
 const [period,setPeriod]=useState<'today'|'week'|'month'|'all'>('today'),[sales,setSales]=useState<Sale[]>([]),[month,setMonth]=useState('');
 const token=()=>{const t=getAccessToken();return t?{Authorization:'Bearer '+t}:{}};
 async function loadCustomers(q=search,p=page){const t=getAccessToken();if(!t){setLoading(false);setError('Sign in to load live customer data.');return}setLoading(true);setError('');try{const params=new URLSearchParams({page:String(p),limit:'25'});if(q.trim())params.set('search',q.trim());const data=await apiFetch<Response>('/customers?'+params,{headers:{Authorization:'Bearer '+t}});setCustomers(data.data||[]);setPagination(data.pagination);setPage(p)}catch(e){setError(e instanceof Error?e.message:'Unable to load customers')}finally{setLoading(false)}}
 async function loadSales(nextPeriod=period,nextMonth=month){try{const suffix=nextMonth?'&month='+encodeURIComponent(nextMonth):'';const r=await apiFetch<{data:Sale[]}>('/sales/customers?period='+nextPeriod+suffix,{headers:token()});setSales(r.data||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load customer history')}}
 useEffect(()=>{void loadCustomers('',1);void loadSales('today','')},[]);
 async function createCustomer(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{await apiFetch('/customers',{method:'POST',headers:{...token(),'Content-Type':'application/json'},body:JSON.stringify(form)});setForm({fullName:'',username:'',email:'',phone:''});await loadCustomers(search,1)}catch(e){setError(e instanceof Error?e.message:'Unable to create customer')}finally{setSaving(false)}}
 return <main className='customer-page'><header><div><div className='eyebrow'>JASLYN NET / CUSTOMER OPERATIONS</div><h1>Customers</h1><p>Customer directory plus period-based purchase history, order IDs and payment references.</p></div><button className='primary' onClick={()=>document.getElementById('new-customer')?.scrollIntoView({behavior:'smooth'})}>+ New customer</button></header>{error&&<div className='notice'>{error}</div>}
 <section className='insights'><article><span>Customers online</span><strong>Live sessions</strong><small>Use Sessions for authoritative live connectivity.</small></article><article><span>Today</span><strong>{period==='today'?sales.length:'—'}</strong><small>purchase records</small></article><article><span>This week</span><strong>{period==='week'?sales.length:'—'}</strong><small>purchase records</small></article><article><span>This month</span><strong>{period==='month'?sales.length:'—'}</strong><small>purchase records</small></article></section>
 <section className='panel history'><div className='head'><div><div className='kicker'>CUSTOMER HISTORY</div><h2>Today's customers</h2></div><div className='periods'>{(['today','week','month','all'] as const).map(x=><button className={period===x?'active':''} key={x} onClick={()=>{setPeriod(x);void loadSales(x, x==='month'?month:'')}}>{x}}</button>)}</div></div><div className='browse'><label>Browse by month<input type='month' value={month} onChange={e=>{setMonth(e.target.value);setPeriod('month');void loadSales('month',e.target.value)}}/></label></div><div className='table'><div className='row head'><span>CUSTOMER ID</span><span>PHONE</span><span>ORDER ID</span><span>REFERENCE</span><span>PACKAGE</span><span>START</span></div>{sales.length?sales.map(x=><div className='row' key={x.orderId}><span>{x.customerId.slice(0,10)}…</span><span>{x.phone||'—'}</span><span>{x.orderId.slice(0,10)}…</span><span>{x.paymentReference||'—'}</span><span>{x.packageName}</span><span>{new Date(x.startsAt).toLocaleString()}</span></div>):<div className='empty'>No customer purchases in this period.</div>}</div></section>
 <section className='layout'><article className='panel'><div className='head'><div><div className='kicker'>CUSTOMER DIRECTORY</div><h2>{pagination.total.toLocaleString()} customers</h2></div><form onSubmit={e=>{e.preventDefault();setPage(1);void loadCustomers(search,1)}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder='Phone, name, username, email…'/><button>Search</button></form></div><div className='table'><div className='row directory-head'><span>Customer</span><span>Contact</span><span>Username</span><span>Status</span><span>Joined</span></div>{loading?<div className='empty'>Loading…</div>:customers.map(c=><div className='row directory' key={c.id}><span><b>{c.fullName||'Unnamed'}</b><small>{c.email||'No email'}</small></span><span>{c.phone||'—'}</span><span>{c.username||'—'}</span><span>{c.isActive?'Active':'Inactive'}</span><span>{c.createdAt?new Date(c.createdAt).toLocaleDateString():'—'}</span></div>)}</div>{pagination.pages>1&&<div className='pager'><button disabled={page<=1} onClick={()=>void loadCustomers(search,page-1)}>Previous</button><span>{page} / {pagination.pages}</span><button disabled={page>=pagination.pages} onClick={()=>void loadCustomers(search,page+1)}>Next</button></div>}</article>
 <article className='panel create' id='new-customer'><div className='kicker'>ACCOUNT PROVISIONING</div><h2>Create customer</h2><form onSubmit={create}><label>Full name<input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>Username<input required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Email<input type='email' value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><button className='primary' disabled={saving}>{saving?'Creating…':'Create customer'}</button></form></article></section>
 <style jsx>{`.customer-page{min-height:100vh;background:#f6f8fb;color:#172033;padding:34px 42px}.customer-page header{display:flex;justify-content:space-between;max-width:1500px;margin-bottom:18px}.eyebrow,.kicker{font-size:8px;font-weight:800;letter-spacing:.13em;color:#8a96a8}.customer-page h1{font-size:28px;margin:6px 0 4px}.customer-page header p{font-size:11px;color:#7d899a;margin:0}.primary{height:36px;border:0;border-radius:7px;background:#2563eb;color:#fff;padding:0 13px;font-size:9px;font-weight:800}.notice{max-width:1500px;background:#fff3f4;color:#b64b57;padding:10px;border-radius:7px;font-size:9px;margin-bottom:12px}.insights{max-width:1500px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:12px}.insights article,.panel{background:#fff;border:1px solid #e2e7ee;border-radius:10px;padding:17px}.insights span,.insights small{display:block;font-size:8px;color:#8a95a4}.insights strong{display:block;font-size:18px;margin:6px 0}.layout{max-width:1500px;display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:12px}.history{max-width:1500px;margin-bottom:12px}.head{display:flex;justify-content:space-between;gap:12px;align-items:center}.head h2,.create h2{font-size:15px;margin:6px 0}.periods{display:flex;gap:5px}.periods button,.head form button,.pager button{border:1px solid #dfe4eb;background:#fff;border-radius:6px;padding:7px 9px;font-size:8px}.periods .active{background:#2563eb;color:#fff;border-color:#2563eb}.browse{margin:10px 0}.browse label{font-size:8px;color:#69768a}.browse input{display:block;margin-top:4px;height:34px;border:1px solid #dfe4eb;border-radius:6px;padding:0 8px}.table{margin-top:12px;overflow:auto}.row{display:grid;grid-template-columns:1.3fr 1fr 1.2fr 1.2fr 1.3fr 1.2fr;gap:9px;padding:10px 7px;border-bottom:1px solid #edf0f4;font-size:8px;align-items:center;min-width:760px}.row.head,.directory-head{font-size:7px;color:#98a2af;font-weight:800;letter-spacing:.06em}.row small{display:block;color:#9aa4b1;font-size:7px;margin-top:3px}.directory{grid-template-columns:1.5fr 1fr 1fr .7fr .8fr}.create form{display:grid;gap:11px}.create label{font-size:8px;font-weight:750;color:#69768a}.create input{display:block;width:100%;height:36px;margin-top:5px;border:1px solid #dfe4eb;border-radius:7px;padding:0 9px;font-size:9px}.empty{text-align:center;padding:38px;color:#8a95a4;font-size:9px;min-width:760px}.pager{display:flex;justify-content:flex-end;gap:10px;align-items:center;margin-top:12px;font-size:8px}@media(max-width:1000px){.layout{grid-template-columns:1fr}.insights{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.customer-page{padding:20px 13px}.customer-page header{flex-direction:column}.insights{grid-template-columns:1fr 1fr}.head{align-items:flex-start;flex-direction:column}.periods{overflow:auto}.layout{display:block}.create{margin-top:12px}}`}</style></main>;
}