'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { apiFetch } from '../../lib/api';
import { getAccessToken } from '../../lib/auth';
type Voucher={id:string;code:string;packageId:string;packageName:string;status:string;expiresAt?:string|null;usedAt?:string|null;deviceLimit?:number;batchId?:string|null;codeFormat?:string;printSize?:string;printStyle?:string};
type Package={id:string;name:string;price:string|number;currency:string;durationSeconds:number;isActive:boolean;isFreeTrial?:boolean;devicesPerCode?:number};
const date=(v?:string|null)=>!v?'No expiry':new Date(v).toLocaleString();
const duration=(s:number)=>s%86400===0?(s/86400)+' day':s%3600===0?(s/3600)+' hour':Math.max(1,Math.floor(s/60))+' min';
export default function VouchersPage(){
 const [vouchers,setVouchers]=useState<Voucher[]>([]),[packages,setPackages]=useState<Package[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const [batch,setBatch]=useState({packageId:'',quantity:'10',expires:'2592000',format:'LETTERS_NUMBERS',size:'MINI',style:'CLASSIC'});
 const [lastBatch,setLastBatch]=useState<{codes:string[];packageId:string;printSize:string;printStyle:string}|null>(null);
 const token=()=>{const t=getAccessToken();return t?{Authorization:'Bearer '+t}:{}};
 const load=useCallback(async()=>{setLoading(true);setError('');try{const h=token();const [v,p]=await Promise.all([apiFetch<{data:Voucher[]}>('/vouchers',{headers:h}),apiFetch<{data:Package[]}>('/packages?limit=100&activeOnly=true',{headers:h})]);setVouchers(v.data||[]);setPackages(p.data||[]);setBatch(x=>({...x,packageId:x.packageId||(p.data?.[0]?.id||'')}))}catch(e){setError(e instanceof Error?e.message:'Unable to load vouchers')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function create(e:FormEvent){e.preventDefault();setSaving(true);setError('');setSuccess('');try{const result=await apiFetch<{count:number;codes:string[];packageId:string;printSize:string;printStyle:string}>('/vouchers/batches',{method:'POST',headers:{...token(),'Content-Type':'application/json'},body:JSON.stringify({packageId:batch.packageId,quantity:Number(batch.quantity),expiresInSeconds:Number(batch.expires),codeFormat:batch.format,printSize:batch.size,printStyle:batch.style})});setLastBatch(result);setSuccess('Generated '+result.count+' voucher codes.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to generate vouchers')}finally{setSaving(false)}}
 function quickTrial(){const trial=packages.find(p=>p.isFreeTrial);if(trial)setBatch(x=>({...x,packageId:trial.id,quantity:'10'}));else setError('Create a package with Free Trial enabled first.')}
 function print(){if(!lastBatch)return;const title='JASLYN NET VOUCHERS';const body=lastBatch.codes.map(code=>'<div class="voucher"><b>'+code+'</b><span>'+lastBatch.printStyle+'</span></div>').join('');const w=window.open('','_blank','width=900,height=700');if(!w)return;w.document.write('<!doctype html><html><head><title>'+title+'</title><style>body{font-family:Arial;padding:20px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.voucher{border:1px solid #ddd;padding:12px;border-radius:8px;display:flex;justify-content:space-between}.voucher b{font-size:18px;letter-spacing:2px}.voucher span{font-size:9px;color:#777}</style></head><body><h2>'+title+'</h2><div class="grid">'+body+'</div><script>window.print()</script></body></html>');w.document.close()}
 const unused=vouchers.filter(v=>v.status==='UNUSED').length,used=vouchers.filter(v=>v.status==='USED').length,expired=vouchers.filter(v=>v.status==='EXPIRED').length;
 return <main className='voucher-page'><header><div><div className='eyebrow'>JASLYN NET / COMMERCIAL OPERATIONS</div><h1>Vouchers</h1><p>Generate, format, print and redeem prepaid access codes without leaving the tenant control plane.</p></div><button onClick={()=>void load()} disabled={loading}>Refresh</button></header>{error&&<div className='notice error'>{error}</div>}{success&&<div className='notice success'>{success}</div>}
 <section className='kpis'><article><span>Total</span><strong>{vouchers.length}</strong></article><article><span>Unused</span><strong>{unused}</strong></article><article><span>Redeemed</span><strong>{used}</strong></article><article><span>Expired</span><strong>{expired}</strong></article></section>
 <section className='panel'><div className='kicker'>GENERATE VOUCHERS</div><h2>Batch provisioning</h2><form onSubmit={create} className='form'><label>Package<select required value={batch.packageId} onChange={e=>setBatch({...batch,packageId:e.target.value})}>{packages.map(p=><option key={p.id} value={p.id}>{p.name} · {p.currency} {Number(p.price).toLocaleString()} · {duration(p.durationSeconds)}{p.isFreeTrial?' · FREE TRIAL':''}</option>)}</select></label><button type='button' className='quick' onClick={quickTrial}>Quick fill: free test package</button><div className='two'><label>Quantity<input type='number' min='1' max='10000' value={batch.quantity} onChange={e=>setBatch({...batch,quantity:e.target.value})}/></label><label>Expiry seconds<input type='number' min='60' max='31536000' value={batch.expires} onChange={e=>setBatch({...batch,expires:e.target.value})}/></label></div><label>Code format<select value={batch.format} onChange={e=>setBatch({...batch,format:e.target.value})}><option value='LETTERS_NUMBERS'>Letters and numbers</option><option value='NUMBERS'>Numbers only</option><option value='LETTERS'>Letters only</option></select></label><div className='two'><label>Print size<select value={batch.size} onChange={e=>setBatch({...batch,size:e.target.value})}><option value='MINI'>Mini 54 × 27 mm</option><option value='THERMAL'>Thermal</option><option value='A4'>A4</option></select></label><label>Style<select value={batch.style} onChange={e=>setBatch({...batch,style:e.target.value})}><option value='CLASSIC'>Classic</option><option value='COMPACT'>Compact</option><option value='BRANDED'>Branded</option></select></label></div><button className='primary' disabled={saving}>{saving?'Generating…':'Generate vouchers'}</button></form>{lastBatch&&<div className='batch-actions'><button className='primary' type='button' onClick={print}>Print generated codes</button><span>{lastBatch.codes.length} codes ready</span></div>}</section>
 <section className='panel'><div className='kicker'>VOUCHER LEDGER</div><h2>{vouchers.length.toLocaleString()} recent codes</h2><div className='table'><div className='tr head'><span>CODE</span><span>PACKAGE</span><span>STATUS</span><span>CREATED / USED</span></div>{loading?<div className='empty'>Loading…</div>:vouchers.map(v=><div className='tr' key={v.id}><code>{v.code}</code><span>{v.packageName}<small>{v.deviceLimit||1} device allowance</small></span><span className={'status '+v.status.toLowerCase()}>{v.status}</span><span>{date(v.usedAt||v.expiresAt)}</span></div>)}</div></section>
 <style jsx>{`.voucher-page{min-height:100vh;background:#f6f8fb;color:#172033;padding:34px 42px}.voucher-page header{display:flex;justify-content:space-between;max-width:1500px;margin-bottom:18px}.eyebrow,.kicker{font-size:8px;font-weight:800;letter-spacing:.13em;color:#8a96a8}.voucher-page h1{font-size:28px;margin:6px 0 4px}.voucher-page p{font-size:11px;color:#7d899a;margin:0}.voucher-page header button{height:35px;border:1px solid #dfe4eb;background:#fff;border-radius:7px;padding:0 12px}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;max-width:1500px;margin-bottom:12px}.kpis article,.panel{background:#fff;border:1px solid #e2e7ee;border-radius:10px;padding:17px}.kpis span{font-size:8px;color:#8a95a4}.kpis strong{display:block;font-size:22px;margin-top:5px}.panel{max-width:1500px;margin-bottom:12px}.panel h2{font-size:15px;margin:6px 0 15px}.form{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:10px;align-items:end}.form label{font-size:8px;font-weight:750;color:#69768a}.form input,.form select{display:block;width:100%;height:36px;margin-top:5px;border:1px solid #dfe4eb;border-radius:7px;padding:0 9px;font-size:9px}.form .two{display:contents}.quick{height:36px;border:1px solid #dfe4eb;border-radius:7px;background:#f7f9fc;font-size:8px}.primary{height:38px;border:0;border-radius:7px;background:#2563eb;color:#fff;font-size:9px;font-weight:800}.batch-actions{margin-top:12px;padding-top:12px;border-top:1px solid #edf0f4;display:flex;align-items:center;gap:10px}.batch-actions span{font-size:8px;color:#7d899a}.notice{max-width:1500px;padding:10px;border-radius:7px;margin-bottom:12px;font-size:9px}.error{background:#fff3f4;color:#b34d58}.success{background:#edf9f2;color:#2f7d58}.table{margin-top:12px}.tr{display:grid;grid-template-columns:1.1fr 2fr .8fr 1.2fr;gap:10px;padding:11px 8px;border-bottom:1px solid #edf0f4;font-size:9px;align-items:center}.tr.head{font-size:7px;font-weight:800;color:#98a2af;letter-spacing:.08em}.tr small{display:block;font-size:7px;color:#9aa4b1;margin-top:3px}.tr code{font-size:10px;letter-spacing:.08em}.status{font-size:7px;font-weight:800;padding:4px 6px;border-radius:4px;width:max-content}.status.unused{background:#edf7f1;color:#2f805d}.status.used{background:#eef2f6;color:#6d7889}.status.expired{background:#fff0f1;color:#b64b57}.empty{text-align:center;padding:45px;color:#8a95a4;font-size:10px}@media(max-width:1000px){.form{grid-template-columns:1fr 1fr}.kpis{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.voucher-page{padding:20px 13px}.voucher-page header{flex-direction:column;gap:10px}.form{grid-template-columns:1fr}.tr{grid-template-columns:1fr 1fr}.tr.head{display:none}}`}</style></main>;
}