'use client';

import { FormEvent, useEffect, useState } from 'react';
import { getAccessToken } from '../../lib/auth';
import { apiFetch } from '../../lib/api';

type Package={id:string;name:string;price:string|number;currency:string;durationSeconds:number;dataLimitBytes?:number|null;downloadBps?:number|null;uploadBps?:number|null;devicesPerCode:number;showOnPortal:boolean;isFreeTrial:boolean;freeTrialFrequency:string;isActive:boolean};
type Response={data:Package[];pagination:{page:number;limit:number;total:number;pages:number}};
const duration=(s:number)=>s%86400===0?(s/86400)+' day'+(s===86400?'':'s'):s%3600===0?(s/3600)+' hour'+(s===3600?'':'s'):Math.max(1,Math.floor(s/60))+' min';
const speed=(bps?:number|null)=>!bps?'Unlimited':Math.round(bps/1000000)+' Mbps';

export default function PackagesPage(){
 const [rows,setRows]=useState<Package[]>([]),[pagination,setPagination]=useState<Response['pagination']>({page:1,limit:25,total:0,pages:0}),[pageNo,setPageNo]=useState(1),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({name:'',price:'',duration:'1',unit:'day',dataGb:'',down:'',up:'',devices:'1',show:true,trial:false,frequency:'ONCE_PER_PHONE'});
 const token=()=>{const t=getAccessToken();return t?{Authorization:'Bearer '+t}:{}};
 async function load(p=pageNo,q=search){setLoading(true);setError('');try{const data=await apiFetch<Response>('/packages?'+new URLSearchParams({page:String(p),limit:'25',...(q.trim()?{search:q.trim()}: {})}),{headers:token()});setRows(data.data||[]);setPagination(data.pagination);setPageNo(p)}catch(e){setError(e instanceof Error?e.message:'Unable to load packages')}finally{setLoading(false)}}
 useEffect(()=>{void load(1,'')},[]);
 async function create(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{const units:Record<string,number>={minute:60,hour:3600,day:86400,week:604800,month:2592000};await apiFetch('/packages',{method:'POST',headers:{...token(),'Content-Type':'application/json'},body:JSON.stringify({name:form.name.trim(),price:Number(form.price),durationSeconds:Number(form.duration)*units[form.unit],dataLimitBytes:form.dataGb?Number(form.dataGb)*1000000000:undefined,downloadBps:form.down?Number(form.down)*1000000:undefined,uploadBps:form.up?Number(form.up)*1000000:undefined,devicesPerCode:Number(form.devices),showOnPortal:form.show,isFreeTrial:form.trial,freeTrialFrequency:form.frequency})});setForm({...form,name:'',price:''});await load(1,search)}catch(e){setError(e instanceof Error?e.message:'Unable to create package')}finally{setSaving(false)}}
 return <main className='package-page'><header><div className='eyebrow'>JASLYN NET / COMMERCIAL OPERATIONS</div><h1>Plans & Products</h1><p>Packages control price, duration, traffic policy, device allowance and customer-portal visibility.</p></header>{error&&<div className='notice'>{error}</div>}
 <section className='layout'><article className='panel'><div className='head'><div><div className='kicker'>SERVICE CATALOGUE</div><h2>{pagination.total.toLocaleString()} packages</h2></div><form onSubmit={e=>{e.preventDefault();void load(1,search)}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder='Search packages…'/><button>Search</button></form></div>{loading?<div className='empty'>Loading…</div>:!rows.length?<div className='empty'>No packages yet.</div>:<div className='cards'>{rows.map(p=><article className='card' key={p.id}><div className='badges'><span className={p.isActive?'on':'off'}>{p.isActive?'ACTIVE':'INACTIVE'}</span><span>{p.showOnPortal?'ON PORTAL':'PRIVATE'}</span>{p.isFreeTrial&&<span className='trial'>FREE TRIAL</span>}</div><h3>{p.name}</h3><strong>{p.currency} {Number(p.price).toLocaleString()}</strong><p>{duration(p.durationSeconds)} · {speed(p.downloadBps)} ↓ / {speed(p.uploadBps)} ↑</p><small>{p.dataLimitBytes?(p.dataLimitBytes/1000000000).toFixed(1)+' GB cap':'Unlimited data'} · {p.devicesPerCode} device{p.devicesPerCode===1?'':'s'} per code</small>{p.isFreeTrial&&<small>Trial frequency: {p.freeTrialFrequency.replaceAll('_',' ')}</small>}</article>)}</div>}{pagination.pages>1&&<div className='pager'><button disabled={pageNo<=1} onClick={()=>void load(pageNo-1)}>Previous</button><span>{pageNo} / {pagination.pages}</span><button disabled={pageNo>=pagination.pages} onClick={()=>void load(pageNo+1)}>Next</button></div>}</article>
 <article className='panel create'><div className='kicker'>NEW PACKAGE</div><h2>Create package</h2><form onSubmit={create}><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder='Jina'/></label><div className='two'><label>Duration<input type='number' min='1' required value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></label><label>Unit<select value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}><option value='minute'>minute</option><option value='hour'>hour</option><option value='day'>day</option><option value='week'>week</option><option value='month'>month</option></select></label></div><label>Price (TZS)<input type='number' min='0' required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><div className='two'><label>Speed down Mbps<input type='number' min='1' value={form.down} onChange={e=>setForm({...form,down:e.target.value})} placeholder='Unlimited'/></label><label>Speed up Mbps<input type='number' min='1' value={form.up} onChange={e=>setForm({...form,up:e.target.value})} placeholder='Unlimited'/></label></div><div className='two'><label>Data cap GB<input type='number' min='1' value={form.dataGb} onChange={e=>setForm({...form,dataGb:e.target.value})} placeholder='Unlimited'/></label><label>Devices per code<select value={form.devices} onChange={e=>setForm({...form,devices:e.target.value})}>{[1,2,3,4,5,10].map(n=><option key={n} value={n}>{n} device{n===1?'':'s'}</option>)}</select></label></div><label className='check'><input type='checkbox' checked={form.show} onChange={e=>setForm({...form,show:e.target.checked})}/><span>Show on customer portal</span></label><div className='trial'><strong>KIFURUSHI CHA MAJARIBIO</strong><small>Allow a free test package and control how often it can be claimed.</small><label className='check'><input type='checkbox' checked={form.trial} onChange={e=>setForm({...form,trial:e.target.checked})}/><span>Enable free trial</span></label>{form.trial&&<select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value='ONCE_PER_PHONE'>Once ever per phone</option><option value='ONCE_PER_CUSTOMER'>Once ever per customer</option><option value='UNLIMITED'>No claim limit</option></select>}</div><button className='primary' disabled={saving}>{saving?'Creating…':'Create package'}</button></form></article></section>
 <style jsx>{`.package-page{min-height:100vh;background:#f6f8fb;color:#172033;padding:34px 42px}.package-page header{max-width:1500px;margin-bottom:18px}.eyebrow,.kicker{font-size:8px;font-weight:800;letter-spacing:.13em;color:#8a96a8}.package-page h1{font-size:28px;margin:6px 0 4px}.package-page header p{font-size:11px;color:#7d899a;margin:0}.layout{max-width:1500px;display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:12px}.panel{background:#fff;border:1px solid #e2e7ee;border-radius:11px;padding:18px}.head{display:flex;justify-content:space-between;gap:12px;align-items:center}.head h2,.create h2{font-size:15px;margin:6px 0}.head form{display:flex;height:34px}.head input{min-width:260px;border:1px solid #dfe4eb;padding:0 9px;border-radius:7px 0 0 7px;font-size:9px}.head button{border:1px solid #dfe4eb;border-left:0;background:#f7f9fc;border-radius:0 7px 7px 0;font-size:8px;padding:0 10px}.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:15px}.card{border:1px solid #e6eaf0;border-radius:9px;padding:14px;background:#fcfdff}.badges{display:flex;gap:5px;flex-wrap:wrap}.badges span{font-size:6px;font-weight:800;padding:4px 6px;border-radius:4px;background:#eef2f6;color:#6e7a8d}.badges .on{background:#eaf7f0;color:#2f8c62}.badges .off{background:#fff0f1;color:#b64b57}.badges .trial{background:#fff7e8;color:#a36a18}.card h3{font-size:13px;margin:12px 0 6px}.card>strong{font-size:19px}.card p,.card small{display:block;font-size:8px;color:#7d899a;margin:6px 0 0}.create form{display:grid;gap:10px}.create label{font-size:8px;font-weight:750;color:#68758a}.create input,.create select,.trial select{display:block;width:100%;height:36px;margin-top:5px;border:1px solid #dfe4eb;border-radius:7px;background:#fff;padding:0 9px;font-size:9px}.two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.check{display:flex!important;align-items:center;gap:7px}.check input{width:auto!important;margin:0!important}.trial{padding:11px;border:1px solid #e6eaf0;border-radius:8px;background:#f8fafc;display:grid;gap:7px}.trial strong{font-size:9px}.trial small{font-size:7px;color:#7d899a}.primary{height:38px;border:0;border-radius:7px;background:#2563eb;color:#fff;font-size:9px;font-weight:800}.notice{max-width:1500px;margin-bottom:12px;padding:10px;border-radius:7px;background:#fff3f4;color:#b34d58;font-size:9px}.empty{text-align:center;padding:55px;color:#8a95a4;font-size:10px}.pager{display:flex;justify-content:flex-end;gap:10px;align-items:center;margin-top:13px;font-size:8px}.pager button{border:1px solid #dfe4eb;background:#fff;border-radius:6px;padding:7px 9px;font-size:8px}.pager button:disabled{opacity:.4}@media(max-width:1000px){.layout{grid-template-columns:1fr}}@media(max-width:650px){.package-page{padding:20px 13px}.head{flex-direction:column;align-items:stretch}.head form{width:100%}.head input{min-width:0;flex:1}.cards{grid-template-columns:1fr}.two{grid-template-columns:1fr}}`}</style></main>;
}