'use client';

import { useCallback, useEffect, useState } from 'react';
import { ApiError, apiFetch } from '../../lib/api';
import { getAccessToken } from '../../lib/auth';

type Payment = { id:string; customerId?:string|null; purchaseId?:string|null; provider:string; providerReference?:string|null; amount:number|string; currency:string; status:string; createdAt:string; updatedAt:string };
type Method = { code:string; name?:string; currencies?:string[]; configured?:boolean; enabled?:boolean };

function fmtDate(v?:string){ if(!v)return '—'; const d=new Date(v); return Number.isNaN(d.getTime())?'Invalid timestamp':d.toLocaleString(); }
function money(v:number|string,c:string){ const n=Number(v); return Number.isFinite(n)?new Intl.NumberFormat(undefined,{style:'currency',currency:c==='TZS'?'TZS':c,maximumFractionDigits:2}).format(n):'—'; }

export default function PaymentsPage(){
 const [payments,setPayments]=useState<Payment[]>([]); const [methods,setMethods]=useState<Method[]>([]);
 const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{const token=getAccessToken();if(!token){setError('Authentication required.');setLoading(false);return;}setLoading(true);setError(null);try{const h={Authorization:`Bearer ${token}`};const [p,m]=await Promise.all([apiFetch<{data:Payment[]}>('/payments',{headers:h}),apiFetch<{data:Method[]}>('/payments/methods',{headers:h})]);setPayments(Array.isArray(p.data)?p.data:[]);setMethods(Array.isArray(m.data)?m.data:[]);}catch(e:unknown){setError(e instanceof ApiError||e instanceof Error?e.message:'Unable to load payment operations.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load()},[load]);
 const successful=payments.filter(p=>p.status==='SUCCESS'); const pending=payments.filter(p=>p.status==='PENDING'); const failed=payments.filter(p=>p.status==='FAILED'); const total=successful.reduce((s,p)=>s+Number(p.amount||0),0);
 return <main className="app-shell"><section className="content" style={{marginLeft:0,width:'100%'}}>
  <header className="topbar"><div><div className="eyebrow">JASLYN NET / BILLING</div><h1>Payment operations</h1><p className="context">Tenant-scoped payment ledger and settlement-provider readiness. Webhooks remain server-verified.</p></div><div className="top-actions"><button className="selector" onClick={()=>void load()} disabled={loading}>{loading?'Refreshing…':'Refresh payments'}</button></div></header>
  {error&&<div className="error-banner" role="alert">{error}</div>}
  <section className="kpi-grid"><article className="kpi"><div className="kpi-label"><span>Successful</span></div><strong>{successful.length}</strong><div className="kpi-foot"><span>SETTLED</span><small>{money(total,'TZS')} recorded</small></div></article><article className="kpi"><div className="kpi-label"><span>Pending</span></div><strong>{pending.length}</strong><div className="kpi-foot"><span>OPEN</span><small>awaiting provider result</small></div></article><article className="kpi"><div className="kpi-label"><span>Failed</span></div><strong>{failed.length}</strong><div className="kpi-foot"><span>FAILED</span><small>requires review</small></div></article><article className="kpi"><div className="kpi-label"><span>Payment methods</span></div><strong>{methods.filter(m=>m.enabled).length}</strong><div className="kpi-foot"><span>ENABLED</span><small>{methods.length} catalog methods</small></div></article></section>
  <section className="panel"><div className="panel-head"><div><div className="panel-kicker">PROVIDER READINESS</div><h2>Payment methods</h2><p>Configured status comes from the tenant payment-provider configuration.</p></div></div><div className="method-grid">{methods.map(m=><article className="method-card" key={m.code}><strong>{m.name??m.code}</strong><small>{m.code}</small><span className={m.enabled?'method-on':'method-off'}>{m.enabled?'ENABLED':'NOT CONFIGURED'}</span></article>)}</div></section>
  <section className="panel"><div className="panel-head"><div><div className="panel-kicker">PAYMENT LEDGER</div><h2>Recent payments</h2><p>{payments.length} records returned by the tenant-scoped API.</p></div></div><div className="table-wrap"><table><thead><tr><th>PAYMENT</th><th>PROVIDER</th><th>AMOUNT</th><th>PURCHASE</th><th>REFERENCE</th><th>STATUS</th><th>CREATED</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td><strong>{p.id.slice(0,8)}…</strong></td><td>{p.provider}</td><td>{money(p.amount,p.currency)}</td><td>{p.purchaseId??'—'}</td><td>{p.providerReference??'—'}</td><td><span className={`status ${p.status.toLowerCase()}`}><i/>{p.status}</span></td><td>{fmtDate(p.createdAt)}</td></tr>)}</tbody></table>{!loading&&!payments.length&&<div className="empty-state"><strong>No payments recorded.</strong><span>Payment records will appear here after a purchase creates a payment intent.</span></div>}{loading&&<div className="empty-state">Loading payment ledger…</div>}</div></section>
  <footer className="footer"><span>JASLYN NET · Payment Operations</span><span>Tenant-scoped ledger</span></footer>
  <style jsx>{`.method-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;padding:0 18px 18px}.method-card{border:1px solid #e8ebf0;border-radius:8px;padding:13px;display:flex;flex-direction:column;gap:5px;min-width:0}.method-card strong{font-size:10px;color:#273247}.method-card small{font-size:8px;color:#8a95a4;overflow:hidden;text-overflow:ellipsis}.method-on,.method-off{font-size:7px;font-weight:800;letter-spacing:.06em;margin-top:4px}.method-on{color:#2f7a58}.method-off{color:#9a6b36}@media(max-width:900px){.method-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:620px){.method-grid{grid-template-columns:1fr}}`}</style>
 </section></main>
}
