'use client';
import { useCallback, useEffect, useState } from 'react';
import { apiFetch } from '../../lib/api';
import { getAccessToken } from '../../lib/auth';
type Summary={period:string;month?:string|null;totals:{online:{count:number;amount:number};voucher:{count:number;amount:number};combined:{count:number;amount:number}};byPackage:Array<{packageName:string;count:number;amount:number}>;bySite:Array<{routerName:string;siteName:string;count:number;amount:number}>};
type CustomerRow={orderId:string;customerId:string;phone?:string;paymentReference?:string;packageName:string;startsAt:string;endsAt:string;amount:number|string;currency:string};
type PaymentRow={paymentId:string;status:string;provider:string;paymentReference?:string;amount:number|string;currency:string;createdAt:string;orderId?:string;customerId?:string;customerName?:string;phone?:string;packageName?:string};
const money=(v:number|string,c='TZS')=>c+' '+Number(v).toLocaleString();
const fmt=(v?:string)=>v?new Date(v).toLocaleString():'—';
export default function SalesPage(){
 const [period,setPeriod]=useState<'today'|'week'|'month'|'all'>('month'),[month,setMonth]=useState(''),[summary,setSummary]=useState<Summary|null>(null),[customers,setCustomers]=useState<CustomerRow[]>([]),[query,setQuery]=useState(''),[payments,setPayments]=useState<PaymentRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const token=(): Record<string,string> => { const t=getAccessToken(); return t ? { Authorization: 'Bearer '+t } : {}; };
 const load=useCallback(async()=>{setLoading(true);setError('');try{const suffix=month?'&month='+encodeURIComponent(month):'';const h=token();const [s,c]=await Promise.all([apiFetch<Summary>('/sales/summary?period='+period+suffix,{headers:h}),apiFetch<{data:CustomerRow[]}>('/sales/customers?period='+period+suffix,{headers:h})]);setSummary(s);setCustomers(c.data||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load sales analytics')}finally{setLoading(false)}},[period,month]);
 useEffect(()=>{void load()},[load]);
 async function search(){if(query.trim().length<2){setPayments([]);return}try{const r=await apiFetch<{data:PaymentRow[]}>('/sales/payments/search?q='+encodeURIComponent(query.trim()),{headers:token()});setPayments(r.data||[])}catch(e){setError(e instanceof Error?e.message:'Payment search failed')}}
 return <main className='sales-page'><header><div><div className='eyebrow'>JASLYN NET / COMMERCIAL OPERATIONS</div><h1>Sales & Revenue</h1><p>Online payments, voucher sales and customer purchase history, split by period, package and site.</p></div><button onClick={()=>void load()} disabled={loading}>Refresh</button></header>{error&&<div className='notice'>{error}</div>}
 <section className='filters'><div className='periods'>{(['today','week','month','all'] as const).map(x=><button key={x} className={period===x?'active':''} onClick={()=>{setPeriod(x);if(x!=='month')setMonth('')}}>{x==='today'?'Today':x==='week'?'This week':x==='month'?'This month':'All time'}</button>)}</div><label>Browse by month<input type='month' value={month} onChange={e=>{setMonth(e.target.value);setPeriod('month')}}/></label></section>
 <section className='kpis'><article><span>Sales today / selected</span><strong>{summary?money(summary.totals.combined.amount):'—'}</strong><small>{summary?.totals.combined.count||0} transactions</small></article><article><span>Online</span><strong>{summary?money(summary.totals.online.amount):'—'}</strong><small>{summary?.totals.online.count||0} payments</small></article><article><span>Voucher</span><strong>{summary?money(summary.totals.voucher.amount):'—'}</strong><small>{summary?.totals.voucher.count||0} redeemed codes</small></article><article><span>Customers</span><strong>{customers.length}</strong><small>purchase records returned</small></article></section>
 <section className='panel'><div className='kicker'>SALES TOTALS</div><h2>Online, voucher & combined</h2><div className='totals'><div><span>ONLINE</span><b>{summary?money(summary.totals.online.amount):'—'}</b></div><div><span>VOUCHER</span><b>{summary?money(summary.totals.voucher.amount):'—'}</b></div><div><span>COMBINED</span><b>{summary?money(summary.totals.combined.amount):'—'}</b></div></div></section>
 <section className='grid'><article className='panel'><div className='kicker'>BY PACKAGE</div><h2>Package sales</h2><div className='table'>{summary?.byPackage.map(x=><div className='row' key={x.packageName}><span>{x.packageName}</span><b>{x.count}</b><strong>{money(x.amount)}</strong></div>)||<div className='empty'>No sales in this period.</div>}</div></article><article className='panel'><div className='kicker'>BY SITE / ROUTER</div><h2>Sales & live network context</h2><div className='table'>{summary?.bySite.map(x=><div className='row' key={x.routerName+x.siteName}><span>{x.siteName}<small>{x.routerName}</small></span><b>{x.count}</b><strong>{money(x.amount)}</strong></div>)||<div className='empty'>No site sales in this period.</div>}</div></article></section>
 <section className='panel'><div className='kicker'>FIND A PAYMENT</div><h2>Customer says they paid and it did not work?</h2><form onSubmit={e=>{e.preventDefault();void search()}} className='search'><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='Phone number, Customer ID, Order ID or payment reference…'/><button>Search</button></form>{payments.length>0&&<div className='table'><div className='row head'><span>CUSTOMER</span><span>PACKAGE</span><span>AMOUNT</span><span>STATUS</span></div>{payments.map(p=><div className='row' key={p.paymentId}><span>{p.customerName||p.customerId||'—'}<small>{p.phone||''}</small></span><span>{p.packageName||'—'}<small>{p.paymentReference||'No reference'}</small></span><strong>{money(p.amount,p.currency)}</strong><b>{p.status}</b></div>)}</div>}</section>
 <section className='panel'><div className='kicker'>CUSTOMERS BY PERIOD</div><h2>Customer purchase history</h2><div className='table'><div className='row head'><span>CUSTOMER ID</span><span>PHONE</span><span>ORDER / REFERENCE</span><span>PACKAGE</span><span>START / END</span></div>{loading?<div className='empty'>Loading…</div>:customers.length?customers.map(c=><div className='row' key={c.orderId}><span>{c.customerId.slice(0,12)}…</span><span>{c.phone||'—'}</span><span>{c.orderId.slice(0,12)}…<small>{c.paymentReference||'—'}</small></span><span>{c.packageName}</span><span>{fmt(c.startsAt)}<small>{fmt(c.endsAt)}</small></span></div>):<div className='empty'>No customer purchases in this period.</div>}</div></section>
 <style jsx>{`.sales-page{min-height:100vh;background:#f6f8fb;color:#172033;padding:34px 42px}.sales-page header{display:flex;justify-content:space-between;max-width:1500px;margin-bottom:18px}.eyebrow,.kicker{font-size:8px;font-weight:800;letter-spacing:.13em;color:#8a96a8}.sales-page h1{font-size:28px;margin:6px 0 4px}.sales-page header p{font-size:11px;color:#7d899a;margin:0}.sales-page header button,.filters button,.filters input,.search button{height:35px;border:1px solid #dfe4eb;background:#fff;border-radius:7px;padding:0 11px;font-size:8px}.filters{max-width:1500px;display:flex;justify-content:space-between;align-items:end;margin-bottom:12px}.periods{display:flex;gap:6px}.periods .active{background:#2563eb;color:#fff;border-color:#2563eb}.filters label{font-size:8px;color:#69768a;font-weight:750}.filters input{display:block;margin-top:5px;padding:0 8px}.kpis{max-width:1500px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:12px}.kpis article{background:#fff;border:1px solid #e2e7ee;border-radius:10px;padding:16px}.kpis span,.kpis small{display:block;color:#8a95a4;font-size:8px}.kpis strong{display:block;font-size:20px;margin:6px 0 3px}.panel{max-width:1500px;background:#fff;border:1px solid #e2e7ee;border-radius:10px;padding:18px;margin-bottom:12px}.panel h2{font-size:15px;margin:6px 0 14px}.totals{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.totals div{padding:13px;border:1px solid #edf0f4;border-radius:8px}.totals span{display:block;font-size:7px;color:#8a95a4}.totals b{display:block;margin-top:7px;font-size:17px}.grid{max-width:1500px;display:grid;grid-template-columns:1fr 1fr;gap:12px}.grid .panel{min-width:0}.table{margin-top:10px}.row{display:grid;grid-template-columns:1.6fr .8fr 1fr;gap:10px;padding:11px 7px;border-bottom:1px solid #edf0f4;font-size:9px;align-items:center}.row.head{font-size:7px;color:#98a2af;font-weight:800}.row small{display:block;font-size:7px;color:#9aa4b1;margin-top:3px}.row strong{text-align:right}.search{display:flex;gap:7px}.search input{flex:1;height:38px;border:1px solid #dfe4eb;border-radius:7px;padding:0 10px;font-size:9px}.search button{background:#2563eb;color:#fff;border-color:#2563eb}.notice{max-width:1500px;padding:10px;background:#fff3f4;color:#b64b57;border-radius:7px;margin-bottom:12px;font-size:9px}.empty{padding:35px;text-align:center;color:#8a95a4;font-size:9px}@media(max-width:900px){.kpis{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}}@media(max-width:650px){.sales-page{padding:20px 13px}.filters{flex-direction:column;align-items:stretch;gap:10px}.periods{overflow:auto}.kpis{grid-template-columns:1fr 1fr}.totals{grid-template-columns:1fr}.row{grid-template-columns:1fr 1fr}.row strong{text-align:left}}`}</style></main>;
}