'use client';

import { useCallback,useEffect,useState } from 'react';
import { ApiError,apiFetch } from '../../lib/api';
import { getAccessToken } from '../../lib/auth';

type Command={id:string;routerId?:string|null;commandType:string;actor:string;provider?:string|null;status:string;attempts:number;error?:string|null;correlationId?:string|null;createdAt:string;sentAt?:string|null;completedAt?:string|null;verifiedAt?:string|null};
const STATUSES=['ALL','QUEUED','SENT','ACCEPTED','EXECUTED','VERIFIED','FAILED','RETRYING','ABANDONED'];
function fmt(v?:string|null){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'Invalid timestamp':d.toLocaleString();}
export default function NetworkCommandsPage(){const [rows,setRows]=useState<Command[]>([]);const [status,setStatus]=useState('ALL');const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{const t=getAccessToken();if(!t){setError('Authentication required.');setLoading(false);return;}setLoading(true);setError(null);try{const q=status==='ALL'?'':'?status='+encodeURIComponent(status);const r=await apiFetch<{data:Command[];count:number}>(`/network-commands${q}`,{headers:{Authorization:`Bearer ${t}`}});setRows(Array.isArray(r.data)?r.data:[]);}catch(e:unknown){setError(e instanceof ApiError||e instanceof Error?e.message:'Unable to load network command history.')}finally{setLoading(false)}},[status]);useEffect(()=>{void load()},[load]);
 const verified=rows.filter(r=>r.status==='VERIFIED').length, failed=rows.filter(r=>r.status==='FAILED').length, active=rows.filter(r=>['QUEUED','SENT','ACCEPTED','RETRYING'].includes(r.status)).length;
 return <main className="app-shell"><section className="content" style={{marginLeft:0,width:'100%'}}><header className="topbar"><div><div className="eyebrow">JASLYN NET / NETWORK</div><h1>Network command history</h1><p className="context">Auditable control-plane history for commands dispatched to managed network devices.</p></div><div className="top-actions"><select className="selector" value={status} onChange={e=>setStatus(e.target.value)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><button className="selector" onClick={()=>void load()} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button></div></header>{error&&<div className="error-banner" role="alert">{error}</div>}
 <section className="kpi-grid"><article className="kpi"><div className="kpi-label"><span>Returned</span></div><strong>{rows.length}</strong><div className="kpi-foot"><span>QUERY</span><small>tenant scoped</small></div></article><article className="kpi"><div className="kpi-label"><span>Active</span></div><strong>{active}</strong><div className="kpi-foot"><span>IN FLIGHT</span><small>queued or retrying</small></div></article><article className="kpi"><div className="kpi-label"><span>Verified</span></div><strong>{verified}</strong><div className="kpi-foot"><span>CONFIRMED</span><small>execution verified</small></div></article><article className="kpi"><div className="kpi-label"><span>Failed</span></div><strong>{failed}</strong><div className="kpi-foot"><span>ATTENTION</span><small>operator review</small></div></article></section>
 <section className="panel"><div className="panel-head"><div><div className="panel-kicker">COMMAND AUDIT</div><h2>Dispatch history</h2><p>Read-only operational history. Commands are created by enforcement services and workers.</p></div></div><div className="table-wrap"><table><thead><tr><th>COMMAND</th><th>TYPE</th><th>ROUTER</th><th>PROVIDER</th><th>STATUS</th><th>ATTEMPTS</th><th>CREATED</th><th>COMPLETED</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.id.slice(0,8)}…</strong><br/><small>{r.correlationId??'no correlation id'}</small></td><td>{r.commandType}</td><td>{r.routerId??'—'}</td><td>{r.provider??'—'}</td><td><span className={`status ${r.status.toLowerCase()}`}><i/>{r.status}</span>{r.error&&<small className="row-error">{r.error}</small>}</td><td>{r.attempts}</td><td>{fmt(r.createdAt)}</td><td>{fmt(r.verifiedAt??r.completedAt)}</td></tr>)}</tbody></table>{!loading&&!rows.length&&<div className="empty-state"><strong>No network commands match this filter.</strong><span>Only commands actually persisted by the control plane are displayed.</span></div>}{loading&&<div className="empty-state">Loading command history…</div>}</div></section>
 <footer className="footer"><span>JASLYN NET · Network Command Control</span><span>Read-only audit surface</span></footer><style jsx>{`.row-error{display:block;color:#9b4b4b;margin-top:3px;max-width:280px;white-space:normal}`}</style></section></main>}
