'use client';

import { useCallback,useEffect,useState } from 'react';
import { ApiError,apiFetch } from '../../lib/api';
import { getAccessToken } from '../../lib/auth';

type Nas={id:string;name:string;address:string;authPort:number;accountingPort:number;coaPort:number;enabled:boolean;createdAt:string};
export default function RadiusPage(){
 const [rows,setRows]=useState<Nas[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{const t=getAccessToken();if(!t){setError('Authentication required.');setLoading(false);return;}setLoading(true);setError(null);try{const r=await apiFetch<{data:Nas[]}>('/radius/nas',{headers:{Authorization:`Bearer ${t}`}});setRows(Array.isArray(r.data)?r.data:[])}catch(e:unknown){setError(e instanceof ApiError||e instanceof Error?e.message:'Unable to load RADIUS NAS clients.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 return <main className="app-shell"><section className="content" style={{marginLeft:0,width:'100%'}}><header className="topbar"><div><div className="eyebrow">JASLYN NET / AAA</div><h1>RADIUS control plane</h1><p className="context">Real tenant-scoped NAS registration for the embedded RADIUS authentication and accounting service.</p></div><div className="top-actions"><button className="selector" onClick={()=>void load()} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button></div></header>{error&&<div className="error-banner" role="alert">{error}</div>}
 <section className="kpi-grid"><article className="kpi"><div className="kpi-label"><span>NAS clients</span></div><strong>{rows.length}</strong><div className="kpi-foot"><span>REGISTERED</span><small>tenant scoped</small></div></article><article className="kpi"><div className="kpi-label"><span>Enabled</span></div><strong>{rows.filter(r=>r.enabled).length}</strong><div className="kpi-foot"><span>ACCEPTING</span><small>source IP verified</small></div></article><article className="kpi"><div className="kpi-label"><span>Authentication</span></div><strong>1812</strong><div className="kpi-foot"><span>UDP</span><small>configurable by environment</small></div></article><article className="kpi"><div className="kpi-label"><span>Accounting</span></div><strong>1813</strong><div className="kpi-foot"><span>UDP</span><small>START / INTERIM / STOP</small></div></article></section>
 <section className="panel"><div className="panel-head"><div><div className="panel-kicker">NAS REGISTRY</div><h2>RADIUS clients</h2><p>Shared secrets are encrypted at rest and never returned by the API.</p></div></div><div className="table-wrap"><table><thead><tr><th>NAME</th><th>ADDRESS</th><th>AUTH PORT</th><th>ACCOUNTING</th><th>COA</th><th>STATE</th><th>CREATED</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td><td>{r.address}</td><td>{r.authPort}</td><td>{r.accountingPort}</td><td>{r.coaPort}</td><td><span className={`status ${r.enabled?'active':'disabled'}`}><i/>{r.enabled?'ENABLED':'DISABLED'}</span></td><td>{new Date(r.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{!loading&&!rows.length&&<div className="empty-state"><strong>No RADIUS NAS clients registered.</strong><span>Authentication will reject unknown source addresses rather than accepting arbitrary NAS traffic.</span></div>}{loading&&<div className="empty-state">Loading RADIUS registry…</div>}</div></section>
 <footer className="footer"><span>JASLYN NET · RADIUS / AAA</span><span>PAP authentication · accounting · policy attributes</span></footer></section></main>
}
